version: 1
update_configs:
  - package_manager: 'javascript'
    directory: '/'
    update_schedule: 'daily'
    version_requirement_updates: increase_versions
    automerged_updates:
      - match:
          dependency_type: 'all'
          update_type: 'semver:minor'
    commit_message:
      prefix: 'build'
      include_scope: false
