#!/usr/bin/env node

/**
 * Postinstall script to package PocketPages plugins into +config.js
 *
 * Extracts official pocketpages plugins from node_modules and bundles them
 * into pb_hooks/pages/+config.js. This works around PocketHost not deploying
 * node_modules while keeping plugin code in sync with installed package versions.
 *
 * Runs automatically after `bun install`.
 */

const fs = require('fs');
const path = require('path');

const PLUGIN_PATH = path.join(__dirname, '../node_modules/pocketpages-plugin-auth/dist/index.js');
const OUTPUT_PATH = path.join(__dirname, '../pb_hooks/pages/+config.js');

try {
  // Read the official plugin source
  const pluginSource = fs.readFileSync(PLUGIN_PATH, 'utf8');

  // Extract just the plugin code (remove the module.exports wrapper and #region comments)
  const cleanedSource = pluginSource
    .replace(/^\/\/#region.*$/gm, '') // Remove #region comments
    .replace(/^\/\/#endregion.*$/gm, '') // Remove #endregion comments
    .replace(/^module\.exports = src_default;.*$/gm, '') // Remove module.exports
    .trim();

  // Generate the +config.js file with the bundled plugin
  const configContent = `/// <reference path="../../pb_data/types.d.ts" />

/**
 * PocketPages configuration with official auth plugin code inlined
 * Source: pocketpages-plugin-auth@0.2.2/dist/index.js
 *
 * This file is auto-generated by scripts/prepare-auth.js during 'bun install'
 * Do not edit manually - changes will be overwritten on next install
 */

${cleanedSource}

module.exports = {
  plugins: [
    authPluginFactory
  ],
  debug: false
};
`;

  // Write the generated config
  fs.writeFileSync(OUTPUT_PATH, configContent, 'utf8');

  console.log('✓ Generated pb_hooks/pages/+config.js with official auth plugin');
} catch (error) {
  console.error('Failed to prepare auth plugin:', error.message);
  process.exit(1);
}
