#!/usr/bin/env node

/**
 * Postinstall script to package PocketPages plugins into +config.js
 *
 * Extracts official pocketpages plugins from node_modules and bundles them
 * into pb_hooks/pages/+config.js. This works around PocketHost not deploying
 * node_modules while keeping plugin code in sync with installed package versions.
 *
 * Runs automatically after `bun install`.
 */

const fs = require('fs');
const path = require('path');

const AUTH_PLUGIN_PATH = path.join(__dirname, '../node_modules/pocketpages-plugin-auth/dist/index.js');
const JS_SDK_PLUGIN_PATH = path.join(__dirname, '../node_modules/pocketpages-plugin-js-sdk/dist/index.js');
const OUTPUT_PATH = path.join(__dirname, '../pb_hooks/pages/+config.js');

try {
  // Read both plugin sources
  const authPluginSource = fs.readFileSync(AUTH_PLUGIN_PATH, 'utf8');
  const jsSdkPluginSource = fs.readFileSync(JS_SDK_PLUGIN_PATH, 'utf8');

  // Extract just the plugin code (remove the module.exports wrapper and #region comments)
  const cleanAuth = authPluginSource
    .replace(/^\/\/#region.*$/gm, '') // Remove #region comments
    .replace(/^\/\/#endregion.*$/gm, '') // Remove #endregion comments
    .replace(/^module\.exports = src_default;.*$/gm, '') // Remove module.exports
    .trim();

  const cleanJsSdk = jsSdkPluginSource
    .replace(/^\/\/#region.*$/gm, '')
    .replace(/^\/\/#endregion.*$/gm, '')
    .replace(/^module\.exports = src_default;.*$/gm, '')
    .trim();

  // Generate the +config.js file with both bundled plugins
  const configContent = `/// <reference path="../../pb_data/types.d.ts" />

/**
 * PocketPages configuration with official plugins inlined
 * Sources:
 * - pocketpages-plugin-js-sdk@0.2.0/dist/index.js
 * - pocketpages-plugin-auth@0.2.2/dist/index.js
 *
 * This file is auto-generated by scripts/package-plugins.js during 'bun install'
 * Do not edit manually - changes will be overwritten on next install
 */

${cleanJsSdk}

${cleanAuth}

module.exports = {
  plugins: [
    jsSdkPluginFactory,
    authPluginFactory
  ],
  debug: false
};
`;

  // Write the generated config
  fs.writeFileSync(OUTPUT_PATH, configContent, 'utf8');

  console.log('✓ Generated pb_hooks/pages/+config.js with js-sdk and auth plugins');
} catch (error) {
  console.error('Failed to prepare auth plugin:', error.message);
  process.exit(1);
}
