name: Master - Build and Deploy
on:
  push:
    branches:
      - master
jobs:
  re-check:
    strategy:
      fail-fast: false
      matrix:
        command:
          - lint
          - test
    name: ${{ matrix.command }}
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v1
      - uses: actions/setup-node@v2
        with:
          node-version: '17'
      - name: 'Cache'
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
      - name: 'Install dependencies'
        run: yarn install --immutable
      - name: 'Run ${{ matrix.command }}'
        run: yarn ${{ matrix.command }}
        env:
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
  deploy:
    runs-on: ubuntu-latest
    needs: [re-check]
    strategy:
      fail-fast: false
      matrix:
        repo:
          - csi-lk/csi.lk
          - csi-lk/callumsilcock.com
          - csi-lk/xn--ev9h.ml # 🧔
          - csi-lk/xn--g5hx212o.ml # 🧔‍♂️
    steps:
      - name: 'Cache'
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false
      - uses: actions/setup-node@v2
        with:
          node-version: '17'
      - name: 'Install dependencies'
        run: yarn install --immutable
      - name: 'Build'
        run: yarn build:prod
      - name: 'Deploy csi.lk'
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          REPOSITORY_NAME: ${{ matrix.repo }}
          BRANCH: gh-pages
          FOLDER: dist
          GIT_CONFIG_NAME: Callum Silcock
          GIT_CONFIG_EMAIL: code@csi.lk
  notify:
    runs-on: ubuntu-latest
    needs: [deploy]
    steps:
      - name: Slack Notification
        uses: rtCamp/action-slack-notify@master
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_COLOR: '#000'
          SLACK_ICON: https://raw.githubusercontent.com/github/explore/master/topics/actions/actions.png
          SLACK_MESSAGE: 'Deployed https://csi.lk to production :rocket:'
          SLACK_TITLE: Production Deployment
          SLACK_USERNAME: deployBot
