name: Pull Request Check
on: [pull_request]

permissions:
  contents: write
  pull-requests: write

jobs:
  pr_check:
    strategy:
      fail-fast: false
      matrix:
        command:
          - lint:eslint
          - lint:stylelint
          - test
          - build:prod
          - e2e
    name: ${{ matrix.command }}
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v1
      - uses: actions/setup-node@v2
        with:
          node-version: '17'
      - name: 'Cache'
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
      - name: 'Install dependencies'
        run: yarn install --immutable
      - name: 'Run ${{ matrix.command }}'
        run: yarn ${{ matrix.command }}
        env:
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
  commitlint:
    runs-on: ubuntu-latest
    if: github.actor != 'dependabot[bot]'
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v2
        with:
          node-version: '17'
      - name: 'Commitlint'
        uses: wagoid/commitlint-github-action@v1
  dependabot:
    needs: [pr_check]
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' }}
    steps:
      - name: Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@v1
        with:
          github-token: '${{ secrets.GITHUB_TOKEN }}'
      - name: Approve a PR
        run: gh pr review --approve "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - name: Enable auto-merge for Dependabot PRs
        run: gh pr merge --auto --rebase "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
