name: Pull Request Check
on: [pull_request]
jobs:
  pr_check:
    strategy:
      fail-fast: false
      matrix:
        command:
          - lint:eslint
          - lint:stylelint
          - test
          - test:visual
          - build:prod
    name: ${{ matrix.command }}
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v1
      - name: 'Cache'
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
      - name: 'Install dependencies'
        run: yarn install --frozen-lockfile
      - name: 'Run ${{ matrix.command }}'
        run: yarn ${{ matrix.command }}
        env:
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
  commitlint:
    runs-on: ubuntu-latest
    if: github.actor != 'dependabot[bot]'
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: 'Commitlint'
        uses: wagoid/commitlint-github-action@v1
  dependabot:
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]'
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: 'Automerge Dependabot PRs'
        uses: ahmadnassri/action-dependabot-auto-merge@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
